# Generated by Django 5.1.3 on 2024-11-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="URL"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("slug", "parent")},
        ),
    ]
